from __future__ import annotations

import re
from pathlib import Path

from django.db import transaction

from .models import KnowledgeNote, KnowledgeSection, Profile


def clean_transcript_text(raw_text: str) -> str:
    """Remove speaker markers and collapse noisy blank lines."""
    cleaned_lines: list[str] = []
    for line in raw_text.splitlines():
        stripped = line.strip()
        if not stripped:
            cleaned_lines.append("")
            continue
        if stripped.startswith("Speaker "):
            continue
        if stripped.startswith("> Generated by "):
            continue
        cleaned_lines.append(stripped)
    cleaned = "\n".join(cleaned_lines)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def title_from_source_path(source_path: str) -> str:
    stem = Path(source_path).stem
    stem = stem.replace("_逐字稿", "")
    return stem.strip() or "Imported transcript note"


def build_note_payload(title: str, source_path: str, raw_text: str) -> dict:
    cleaned = clean_transcript_text(raw_text)
    paragraphs = [p.strip() for p in cleaned.split("\n\n") if p.strip()]

    keyword_groups = [
        ("內臟脂肪", "内脏脂肪"),
        ("斷食", "断食"),
        ("酮體", "酮体"),
    ]
    if all(any(keyword in cleaned for keyword in group) for group in keyword_groups):
        return {
            "title": title,
            "source_type": KnowledgeNote.SourceType.TRANSCRIPT,
            "source_path": source_path,
            "language_code": "zh-Hant",
            "tags": "fasting, visceral-fat, metabolism, ketones, autophagy, safety",
            "summary": (
                "這篇逐字稿把斷食減少腹部脂肪的過程拆成一條生理時間線：先耗用葡萄糖與肝糖，"
                "再轉向脂肪分解與酮體供能，之後才出現更深層的細胞回收與代謝調整。\n\n"
                "內容強調內臟脂肪對胰島素下降特別敏感，因此在斷食情境下更容易被動員；"
                "但同時也清楚指出長時間斷食的肌肉流失、低血糖與電解質風險，"
                "主張把 16:8 這類可長期執行的方法視為生活方式，而不是極端挑戰。"
            ),
            "raw_text": cleaned,
            "sections": [
                {
                    "heading": "Core question",
                    "heading_zh": "核心問題",
                    "section_type": KnowledgeSection.SectionType.OVERVIEW,
                    "sort_order": 10,
                    "content": (
                        "逐字稿的主軸是：如果一個人持續斷食，直到腹部脂肪，特別是內臟脂肪，明顯下降，"
                        "身體會依序經歷哪些代謝轉換，以及這條路徑的有效邊界和危險邊界在哪裡。"
                    ),
                },
                {
                    "heading": "Fasting timeline",
                    "heading_zh": "斷食時間線",
                    "section_type": KnowledgeSection.SectionType.TIMELINE,
                    "sort_order": 20,
                    "content": (
                        "0-6 小時：主要仍在使用上一餐的葡萄糖，胰島素開始下降。\n"
                        "約 18-24 小時：肝糖接近耗盡，脂肪分解明顯啟動。\n"
                        "24-48 小時：酮體增加，腦部逐步改用酮體，細胞自噬開始被強調。\n"
                        "3-5 天以上：代謝率可能略降，生長激素上升，但肌肉分解與電解質風險也同步增加。"
                    ),
                },
                {
                    "heading": "Why visceral fat responds first",
                    "heading_zh": "為什麼先動員內臟脂肪",
                    "section_type": KnowledgeSection.SectionType.MECHANISM,
                    "sort_order": 30,
                    "content": (
                        "逐字稿把重點放在胰島素下降後的脂肪酶活化。內臟脂肪對胰島素變化更敏感，"
                        "因此當胰島素被壓低時，內臟脂肪通常比皮下脂肪更快進入可分解狀態。"
                        "這也是腰圍有時比體重更早出現變化的原因。"
                    ),
                },
                {
                    "heading": "Main benefits claimed",
                    "heading_zh": "主要潛在益處",
                    "section_type": KnowledgeSection.SectionType.BENEFIT,
                    "sort_order": 40,
                    "content": (
                        "內容把潛在好處整理為：較高的內臟脂肪動員效率、酮體供能下的清醒感、"
                        "胰島素敏感性改善、慢性低度發炎下降，以及脂肪肝與血壓風險可能隨之改善。"
                        "逐字稿同時把這些變化描述為長期生活方式調整的結果，而不是幾天內完成的速效變化。"
                    ),
                },
                {
                    "heading": "Myths and risks",
                    "heading_zh": "常見迷思與風險",
                    "section_type": KnowledgeSection.SectionType.RISK,
                    "sort_order": 50,
                    "content": (
                        "逐字稿反駁三個常見迷思：短期斷食不等於代謝崩潰、短期且脂肪儲備足夠時不一定大量掉肌肉、"
                        "斷食並不代表不能喝水。\n"
                        "但它也明確指出風險：服用降糖藥或胰島素者可能低血糖；孕期、哺乳期、體重過低、"
                        "進食障礙病史、心肝腎疾病患者不適合自行長時間斷食。"
                    ),
                },
                {
                    "heading": "Practical takeaway",
                    "heading_zh": "實務結論",
                    "section_type": KnowledgeSection.SectionType.PRACTICAL,
                    "sort_order": 60,
                    "content": (
                        "這篇內容最適合被轉成可操作的系統筆記，而不是單次挑戰指南。"
                        "可執行結論是把 16:8 或其他非極端斷食方式，和進食窗口內的食物品質、"
                        "體態追蹤、風險提醒一起管理，才能讓『減少內臟脂肪』變成可持續的流程。"
                    ),
                },
            ],
        }

    preview = "\n\n".join(paragraphs[:2])[:600]
    return {
        "title": title,
        "source_type": KnowledgeNote.SourceType.TRANSCRIPT,
        "source_path": source_path,
        "language_code": "zh-Hant",
        "tags": "transcript, imported-note",
        "summary": preview,
        "raw_text": cleaned,
        "sections": [
            {
                "heading": "Imported overview",
                "heading_zh": "匯入摘要",
                "section_type": KnowledgeSection.SectionType.OVERVIEW,
                "sort_order": 10,
                "content": preview or "Imported transcript text.",
            }
        ],
    }


@transaction.atomic
def import_transcript_note(source_path: str, raw_text: str, title: str | None = None) -> KnowledgeNote:
    profile = Profile.objects.order_by("id").first()
    if profile is None:
        profile = Profile.objects.create(display_name="Athlete", height_cm=175.0)

    resolved_title = title or title_from_source_path(source_path)
    payload = build_note_payload(resolved_title, source_path, raw_text)
    sections = payload.pop("sections")

    note, _ = KnowledgeNote.objects.update_or_create(
        profile=profile,
        title=payload["title"],
        defaults=payload,
    )
    note.sections.all().delete()
    KnowledgeSection.objects.bulk_create(
        [KnowledgeSection(note=note, **section) for section in sections]
    )
    return note
