from unittest.mock import Mock, patch

import tempfile
from pathlib import Path

from django.core.management import call_command
from django.test import TestCase, override_settings
from django.urls import reverse

from .models import KnowledgeNote, KnowledgeSection, Profile
from .note_import import clean_transcript_text


class PlanningIntegrationTests(TestCase):
    @override_settings(EXERCISEDB_ENABLED=False, EXERCISEDB_API_KEY="")
    def test_planning_results_falls_back_to_local_library_when_disabled(self):
        response = self.client.get(
            reverse("tracker:planning_results"),
            {"focus": "chest", "goal": "gain", "level": "beginner"},
        )

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Gymweb curated library")
        self.assertContains(response, "Dumbbell bench press")

    @override_settings(EXERCISEDB_ENABLED=True, EXERCISEDB_API_KEY="test-key")
    @patch("tracker.views.ExerciseDbClient.from_settings")
    def test_planning_results_uses_remote_suggestions_when_available(self, mock_from_settings):
        client = Mock()
        client.list_exercises.return_value = {
            "success": True,
            "data": [
                {
                    "name": "Bench Press",
                    "equipments": ["Barbell"],
                    "targetMuscles": ["Pectoralis Major"],
                    "overview": "Classic chest press.",
                    "imageUrl": "https://cdn.example.com/bench.webp",
                }
            ],
        }
        mock_from_settings.return_value = client

        response = self.client.get(
            reverse("tracker:planning_results"),
            {"focus": "chest", "goal": "strength", "level": "intermediate"},
        )

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "ExerciseDB suggestions")
        self.assertContains(response, "Bench Press")
        self.assertContains(response, "https://cdn.example.com/bench.webp")

    @override_settings(EXERCISEDB_ENABLED=True, EXERCISEDB_API_KEY="你的 RapidAPI Key")
    def test_planning_results_falls_back_when_api_key_is_placeholder_text(self):
        response = self.client.get(
            reverse("tracker:planning_results"),
            {"focus": "chest", "goal": "gain", "level": "intermediate"},
        )

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Gymweb curated library")
        self.assertContains(response, "ExerciseDB was unavailable")


class KnowledgeNoteViewTests(TestCase):
    def setUp(self):
        self.profile = Profile.objects.create(display_name="Tester", height_cm=175)

    def test_note_create_view_saves_note_and_redirects(self):
        response = self.client.post(
            reverse("tracker:note_create"),
            {
                "title": "Research note",
                "source_type": KnowledgeNote.SourceType.MANUAL,
                "source_path": "",
                "language_code": "en",
                "tags": "research, notes",
                "summary": "Short summary",
                "raw_text": "Full source text",
            },
        )

        note = KnowledgeNote.objects.get(title="Research note")
        self.assertRedirects(response, reverse("tracker:note_detail", args=[note.slug]))
        self.assertEqual(note.profile.display_name, "Tester")

    def test_note_list_search_matches_section_content(self):
        note = KnowledgeNote.objects.create(
            profile=self.profile,
            title="Fasting overview",
            summary="Summary",
        )
        KnowledgeSection.objects.create(
            note=note,
            heading="Risks",
            heading_zh="風險",
            section_type=KnowledgeSection.SectionType.RISK,
            sort_order=10,
            content="This covers electrolyte safety and low blood sugar.",
        )

        response = self.client.get(reverse("tracker:note_list"), {"q": "electrolyte"})

        self.assertContains(response, "Fasting overview")

    def test_note_detail_route_supports_unicode_slug(self):
        note = KnowledgeNote.objects.create(
            profile=self.profile,
            title="如果斷食直到腹部脂肪消失會發生什麼科學解釋",
            summary="Summary",
        )

        response = self.client.get(reverse("tracker:note_detail", args=[note.slug]))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, note.title)


class KnowledgeImportTests(TestCase):
    def test_clean_transcript_text_removes_speaker_markers(self):
        cleaned = clean_transcript_text("Speaker 1\nHello\n\n> Generated by Tool\nWorld")
        self.assertEqual(cleaned, "Hello\n\nWorld")

    def test_management_command_imports_transcript_as_structured_note(self):
        transcript = (
            "Speaker 1\n"
            "這是一篇關於內臟脂肪與斷食的內容。\n\n"
            "Speaker 1\n"
            "當酮體上升時，身體會進入另一個供能階段。"
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "斷食逐字稿.txt"
            path.write_text(transcript, encoding="utf-8")

            call_command("import_knowledge_note", path=str(path))

        note = KnowledgeNote.objects.get()
        self.assertEqual(note.source_type, KnowledgeNote.SourceType.TRANSCRIPT)
        self.assertTrue(note.sections.exists())
        self.assertNotIn("Speaker 1", note.raw_text)
