# Generated by Django 5.2.12 on 2026-04-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual note'), ('transcript', 'Transcript import'), ('imported', 'Imported article')], default='manual', max_length=20)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('language_code', models.CharField(blank=True, default='zh-Hant', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=240)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_notes', to='tracker.profile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('heading_zh', models.CharField(blank=True, max_length=120)),
                ('section_type', models.CharField(choices=[('overview', 'Overview'), ('timeline', 'Timeline'), ('mechanism', 'Mechanism'), ('benefit', 'Benefit'), ('risk', 'Risk'), ('practical', 'Practical takeaway')], default='overview', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tracker.knowledgenote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
